### ISSUE TITLE
Incorrect behaviour when passing arguments

### ISSUE THREAD

**Issue by niekcandaele** [chabad360/htmlproofer#4]
I'm not sure if I'm doing something wrong or if this is a bug in the image.

In my local terminal, I have this command `htmlproofer --url-ignore "/(docs/edit/master)/" --check-html  docs/.vuepress/dist`. This works and htmlproofer does not return any errors.

In the actions config, I have this

```
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./docs/.vuepress/dist"
          arguments: --url-ignore "/(docs/edit/master)/" --check-html
```

However, it seems that the `--url-ignore "/(docs/edit/master)/"` argument does not get passed correctly. --check-html does work correctly.

An example action log is here: https://github.com/CatalysmsServerManager/docs/pull/82/checks?check_run_id=420831082

Thanks for creating this action, any guidance on this issue is very much appreciated :)
