### ISSUE TITLE
Issues using with Github actions vs. commandline htmlproofer

### ISSUE THREAD

**Issue by Sheeri** [chabad360/htmlproofer#5]
Hello there! When I run htmlproofer on commandline, it works just fine:

```bash
#!/usr/bin/env bash
set -euo pipefail # halt script on error
bundle exec jekyll build   # this builds into _site
bundle exec htmlproofer ./_site --allow-hash-href  --empty-alt-ignore --check_img_http 
```

This is my github workflow yaml file:
```
name: Jekyll site CI with docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
       directory: "./_site"
       arguments: --allow-hash-href  --empty-alt-ignore --check_img_http
```

I get a ton of errors like:

```
External link https://github.com/pages/GITHUB_USER/index.html failed: 404 No error
  *  internal script /pages/GITHUB_USER/assets/js/just-the-docs.js does not exist (line 0)
```

Basically, it's taking https://github.com/pages/GITHUB_USER/ to be the default external webpage (instead of localhost://) and /pages/GITHUB_USER/ to be the default internal webpage (instead of _site).

How can I fix this?

When I run htmlproofer on commandline, I get no problems:

```
Configuration file: /Users/sheeri/github/REPO_NAME/_config.yml
            Source: /Users/sheeri/github/REPO_NAME
       Destination: /Users/sheeri/github/REPO_NAME/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme pmarsceill/just-the-docs
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 6.012 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["./_site"] on *.html... 


Checking 31 external links...
Ran on 41 files!


HTML-Proofer finished successfully.
```
